### PR TITLE
Remove R_CLONE_ENABLED and make clusters-keeper 0 replicas

### PR DESCRIPTION
**Pull request by YuryHrytsuk**
@GitHK, please, confirm that removing `R_CLONE_ENABLED` is safe

@mguidon do we disable somehow clusters-keeper on aws prod? Currently, we have `clusters-keeper replicas: 1` for aws staging and production. May it lead to any unexpected behaviour on aws prod?

### CODE REVIEW

**Review by mrnicegyu11 — APPROVED** [review]
THX

**Comment by YuryHrytsuk** [comment]
R_CLONE related PR: https://github.com/ITISFoundation/osparc-simcore/pull/4502

**Comment by YuryHrytsuk** [comment]
clusters-keeper PR: https://github.com/ITISFoundation/osparc-simcore/pull/4591

**Comment by GitHK** [comment]
totally safe. `R_CLONE_ENABLED` is no longer part of the code

**Pull request merged**
