### PR TITLE
Add Graylog Alert For Unhandled Errors And Exceptions - running every 24h

### PR DESCRIPTION
**Pull request by mrnicegyu11**
Dear backend, I think we should trace and fix unhandled exceptions. This alert might help to remind us that they exist.

Up for debate.

### CODE REVIEW

**Comment by mrnicegyu11** [comment]
I propose we slowly move to try to have "things not to worry about" to not print `Traceback` or `Error`, then this check might help us really find unexpected errors we might skip otherwise

**Review by GitHK — COMMENTED** [review]
@mrnicegyu11 How will this be displayed where will this data go?

**Comment by mrnicegyu11** [comment]
> @mrnicegyu11 How will this be displayed where will this data go?
This would go into the oSparc Batman Mattermost channel as usual. No info about the alerts would be displayed there I guess. But we can adjust this, what do you have in mind?

**Comment by mrnicegyu11** [comment]
merging this before it becomes forgotten, I prefer reverting in case it just creates noise.

**Pull request merged**
