### PR TITLE
✨ Add SmokePing Grafana Dashboard and Prometheus Exporter

### PR DESCRIPTION
**Pull request by mrnicegyu11**
FYI: Adding @mguidon and @matusdrobuliak66 since they might soon work with prometheus or expose metrics to prometheus, so they might find this interesting.

=======================================

This PR addresses https://git.speag.com/oSparc/osparc-ops-environments/-/issues/581 . 

This PR adds:
- Smokeping-Prober Prometheus Exporter https://github.com/SuperQ/smokeping_prober
- Smokeping Grafana Dashboard https://grafana.com/grafana/dashboards/11335-smoke-ping/

The Smokeping dashboard can be used to visualize package drops, package timeouts and networking delays.

In the current configuration, the smokeping-prober will ping (thus via ICMP, not UDP/TCP) the following machines every second and export the timings and whether the ping has been successful to a `/metrics` route which is scraped by prometheus automagically:
- tip.itis.swiss
- osparc-master.speag.com
- osparc.speag.com
- facebook.com
- google.com
- speag.com
- smpt.osparc.io (the ELB loadbalancer of aws which routes `https://osparc.io` does not accept the ICMP protocol, thus we abuse `smtp.osparc.io` to directly go to the manager01 machine of osparc.io)

This is what the grafana dashboard looks like:
image

🚧🚧🚧:
I am not sure that this will work out of the box on all deployments, as I cannot be sure at this point that for example on aws all machines can reach `osparc.speag.com` (due to wireguard, etc.). I guess we will have a look when releasing and adjust accordingly.

Also, since we dont have GitOps yet, these changes to the `monitoring` docker swarm stack need to be rolled out to staging/prod manually.

### CODE REVIEW

**Comment by mrnicegyu11** [comment]
This is what the smokeping-prober exports on `/metrics` (CC @mguidon for s4l prometheus metrics exporting):
```
❯ curl monitoring_smokeping-prober-exporter:9374/metrics
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.75
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 17
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.8481152e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.68612380429e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 7.33261824e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes 1.8446744073709552e+19
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 9
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP smokeping_prober_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which smokeping_prober was built.
# TYPE smokeping_prober_build_info gauge
smokeping_prober_build_info{branch="HEAD",goversion="go1.18.3",revision="8434fd2b1a5584f67f6a5efe70cd851199e7882e",version="0.6.1"} 1
# HELP smokeping_prober_config_last_reload_success_timestamp_seconds Timestamp of the last successful configuration reload.
# TYPE smokeping_prober_config_last_reload_success_timestamp_seconds gauge
smokeping_prober_config_last_reload_success_timestamp_seconds 1.686123805794128e+09
# HELP smokeping_prober_config_last_reload_successful Blackbox exporter config loaded successfully.
# TYPE smokeping_prober_config_last_reload_successful gauge
smokeping_prober_config_last_reload_successful 1
# HELP smokeping_requests_total Number of ping requests sent
# TYPE smokeping_requests_total counter
smokeping_requests_total{host="google.com",ip="142.250.203.110"} 21
[...]
# HELP smokeping_response_duplicates_total The number of duplicated response packets.
# TYPE smokeping_response_duplicates_total counter
smokeping_response_duplicates_total{host="google.com",ip="142.250.203.110"} 0
[...]
# HELP smokeping_response_duration_seconds A histogram of latencies for ping responses.
# TYPE smokeping_response_duration_seconds histogram
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="5e-05"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0001"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0002"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0004"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0008"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0016"} 0
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0032"} 9
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0064"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0128"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0256"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.0512"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.1024"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.2048"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.4096"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="0.8192"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="1.6384"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="3.2768"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="6.5536"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="13.1072"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="26.2144"} 20
smokeping_response_duration_seconds_bucket{host="google.com",ip="142.250.203.110",le="+Inf"} 20
smokeping_response_duration_seconds_sum{host="google.com",ip="142.250.203.110"} 0.066388846
smokeping_response_duration_seconds_count{host="google.com",ip="142.250.203.110"} 20
[...]
# HELP smokeping_response_ttl The last response Time To Live (TTL).
# TYPE smokeping_response_ttl gauge
smokeping_response_ttl{host="google.com",ip="142.250.203.110"} 114
[...]
```

**Review by matusdrobuliak66 — APPROVED** [review]
really nice thanks!

**Review by sanderegg — APPROVED** [review]
looks very nice!!
do they also ping each other nodes?

**Comment by mrnicegyu11** [comment]
> looks very nice!! do they also ping each other nodes?

thanks :) not for now, but since we can supply a list of hosts this is feasible in the future. Feel free to add an enhancement ticket about this in the future once you tried out this initial thing ;)

**Pull request merged**
