### PR TITLE
🚧🚧🚧 Add traefik routing for invitation services

### PR DESCRIPTION
**Pull request by mrnicegyu11**
This adds traefik routing rules for `invitations.osparc.io` and forwards it to the invitation service. It only works with the `MACHINE_FQDN` for now (so, to make this clear, only `invitations.osparc.io` works, not `invitations.s4l-lite.io`). This was tested to work on my local deployment. This should ideally move fast to prod.

🚧🚧🚧: 
 - This deprecates https://git.speag.com/oSparc/invitations and the machines and the repo can be removed.
 - This goes with https://git.speag.com/oSparc/e2e-ops/-/merge_requests/53

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
Question: would it be possible to keep a prefixed host name (i think the right term is subdomain)  i.e. ``invitations.*``  instead of adding as part of the path ??

This way we do not need to notify third parties to change the routing

**Comment by mrnicegyu11** [comment]
It is possible but this complicates the routing a bit, since prefixes (subdomains) are managed by the ops-traefik. If one uses `/invitations`, the routing can be fully handled on the simcore traefik. However, as I notice now (thanks for poiting me in this direction), the invitation service is then affected by the maintenance page (i.e. unavailable if the maintenance page is up). If this is not desirable (and currently there is no urgency), both issues can potentially be addressed. 

let me know again if you think :)

**Review by GitHK — APPROVED** [review]

**Review by matusdrobuliak66 — APPROVED** [review]

**Comment by mrnicegyu11** [comment]
Caught by @Surfict: Entrypoint should be `https` and thus needs `myresolver`

**Comment by mrnicegyu11** [comment]
Todo: Add new subroute to certificates test

**Review by sanderegg — COMMENTED** [review]
should I review this or you are still checking for @pcrespov questions?

**Review by sanderegg — APPROVED** [review]

**Review by pcrespov — APPROVED** [review]
Thx!
Make sure to write a big deprecation/retire note in https://git.speag.com/oSparc/invitations  pointing to the PR

**Pull request merged**
