### PR TITLE
Add pylint pre-commit hook

### PR DESCRIPTION
**Pull request by YuryHrytsuk**
## What do these changes do?
* add pylint pre-commit hook
* refactor files to pass pylint checks 
* update .pylintrc (copy from `osparc-simcore`) + enable `variable names` check

## Related issue/s
* resolves https://github.com/ITISFoundation/osparc-ops-environments/issues/97
* https://github.com/ITISFoundation/osparc-ops-environments/issues/623

## Checklist
- [X] I tested and it works

### CODE REVIEW

**Review by pcrespov — COMMENTED** [review]
This one ready or still draft? :-)
I took the liberty to add the word `resolves` in your related issues to link them. REad this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by YuryHrytsuk** [comment]
> This one ready or still draft? :-) I took the liberty to add the word `resolves` in your related issues to link them. REad this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

It is still in draft. Shall I unassign you until it gets ready?

**Comment by pcrespov** [comment]
> > This one ready or still draft? :-) I took the liberty to add the word `resolves` in your related issues to link them. REad this https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> 
> It is still in draft. Shall I unassign you until it gets ready?

yes please . thx

**Review by pcrespov — COMMENTED** [review]
yes please. @YuryHrytsuk  I meant RE-assign to me for review :-)

**Review by matusdrobuliak66 — APPROVED** [review]
:taco:

**Pull request merged**
